### PR TITLE
Merge with MakiePresentation

### LINKED ISSUE #1: Merge with ffreyer/MakiePresentation
With https://github.com/JuliaPlots/Makie.jl/pull/1818 merged and tagged my attempt at making presentations (https://github.com/ffreyer/MakiePresentation.jl) should be working with the latest release now. With that I think it's reasonable to talk sbout merging our packages.

My goal was to do present using Makie, i.e. to have an interactive Makie window displaying the presentation. A big annoyance with that was that you couldn't really clear a figure, which is what the pr tried to achieve. It's probably still far from perfect, but for this purpose it works well enough.

On the user side my package basically looks like this:
```julia
pres = Presentation()
display(pres)

add_slide!(pres) do fig
    # create your slide as if you had a fresh, empty figure
end

add_slide!(pres, false) do fig
    # with false the previous figure does not get cleared 
    # so you can reveal or adjust existing elements
end
```

Internally there are two figures, one which keeps track of the window and one that has slides drawn on. The first (parent) doesn't get cleared, so it can also be used to add a background image, for example. The other (fig) gets cleared when slides demand it. Other than this I implemented some interactivity to move throuh slides, but that's it. 

From a quick look at your Slide and Presentation structs I think we could replace/merge them with my Presentation struct, though it might be necessary to fix some stuff in Makie for clearing to work correctly with CairoMakie. I would like to keep the Slides empty on creation too, so users keep full control over how they look. As far as I can tell they create 3 Axis objects by default atm?

### PR DESCRIPTION
**Pull request by ffreyer**
This will close #1. For now I've mostly just replaced MakieSlides code with MakiePresentations code and added an example. 

## TODO

- [x] Move MakiePresentations `Presentaion` and slide handling here
- [x] get pdf generation to work
- [x] update layoutable to blocks (because MakiePresentation relies on Makie#0.17 which also itnroduced Blocks)
    - [x] FormattedLabel (Seems buggy though)
    - [x] FormattedList
    - [x] FormattedTable
    - [x] MarkdownBox
- [x] update example
- [x] cleanup

### CODE REVIEW

**Comment by fatteneder** [comment]
Just noticed that you are already merging and preparing the move from `@Layoutables` to `@Blocks`. I was still holding back, because I was drafting things, but updating now makes sense.

I also updated positioning with `FormattedLabel` and it is much better now.

Also moving to a branching workflow for the drafting so to not interfer anymore with this PR.

**Comment by fatteneder** [comment]
I fixed the conflicts over here https://github.com/fatteneder/MakieSlides.jl/tree/fa/resolve-conflicts. Feel free to merge it into here, just did not want to interrupt any progress you made on this.

I got the automatic box height adjustment going again by switching from `layoutboservables.autosize` to `layoutobservables.reportedsize`. Not sure whether this is the right way to do it though ...

Also noticed a bug in line wrapping I introduced yesterday where characters are cut of at the beginning of the line.

**Comment by ffreyer** [comment]
I was already working on merging changes so I just used my version for now.

I've been quite destructive with updating things to blocks and I probably broke some stuff along the way. Though I also don't know how they worked before. It would be good if you went through the changes and repaired the damage I did. I left most of the old code as comments so you can still refer back to a lot of it.

Some problems I noticed:
- lists are not left aligned and have visible boxes as the last entry
- lists use * as markers rather than unicode dots or some other nicer symbols
- tables are completely broken for me. My markdown strings don't have an align field and no rows either
- FormattedLabel is missing characters when wrapping like you mentioned

As a note I replaced some of the layouting code in FormattedLabel with the code I have in the Makie pr because the old version was endlessly looping for me.

As another note I added a "new_mwe.jl" in the example folder which should be working.

**Comment by fatteneder** [comment]
> - lists are not left aligned and have visible boxes as the last entry

They are left aligned for me if I use my version for layouting in `FormattedLabel`, see below. The visible box at the end I have in there to tell its height such that the other labels are all shifted/flushed to the top. It just had a color for debugging. I don't like this solution, do you know of a better approach?

> - lists use * as markers rather than unicode dots or some other nicer symbols

The `itemization_symbol` is there to pick markers. I changed the default to the unicode dot from your MWE.

> - tables are completely broken for me. My markdown strings don't have an align field and no rows either

That's an annoying one. The `Markdown` parser interprets blocks with (I think) two or four spaces or multiples thereof as code blocks, hence, the wrong type. If you left align the whole table within `md""" """` then it works. I am already thinking of moving to `CommonMark.jl` as an alternative Markdown parser, because that one offers more configuration options also for parsing, not sure if this behavior is configurable though ...

> - FormattedLabel is missing characters when wrapping like you mentioned

Fixed.

> As a note I replaced some of the layouting code in FormattedLabel with the code I have in the Makie pr because the old version was endlessly looping for me.

I looked into your version and I remember having something similar when I started (I took it from `Label`). I can't see why it does not left align the text if `FormattedLabel`s are used in a `GridLayout`. For now I changed that back to what I had before, but fixed the infinite update loop by updating now `reporetedsize` instead of `autosize`. Perhaps we can reconsider this whenever line wrapping is merged in `Makie.jl`.


Thanks for doing the `Layoutable` to `Block` refactor for me.
I cleaned up the dead code and with the new `Block` API things look much simpler now.

**Comment by fatteneder** [comment]
I played a bit around with the presentation mode and it works. However, on my machine I notice lag when moving between slides. My first implementation with the one-figure-for-each-slide had some lag too, but I remember it to be less than what I observe now.

Perhaps I should dust out the old implementation and do a comparison. But then we would loose the common parent feature, hmmm :/

**Pull request merged**
